#!/usr/bin/env python3
"""Regenerate INDEX.md: a linked table of every recipe, grouped by domain.

Usage: python3 scripts/gen_index.py   (writes INDEX.md at the repo root)
Run after adding recipes; CI and the README badge count come from the same walk.
"""
import json
import os
import re
from collections import defaultdict

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def frontmatter(path):
    with open(path) as f:
        text = f.read()
    end = text.find("\n---\n", 4)
    if not text.startswith("---\n") or end == -1:
        return {}
    try:
        return yaml.safe_load(text[4:end]) or {}
    except yaml.YAMLError:
        return {}


def main():
    with open(os.path.join(ROOT, "domains.json")) as f:
        domains = json.load(f)

    rows = defaultdict(list)
    total = 0
    for domain in sorted(domains):
        d = os.path.join(ROOT, domain)
        if not os.path.isdir(d):
            continue
        for dirpath, _, names in os.walk(d):
            for n in sorted(names):
                if not n.endswith(".md"):
                    continue
                rel = os.path.relpath(os.path.join(dirpath, n), ROOT)
                meta = frontmatter(os.path.join(dirpath, n))
                rows[domain].append((rel, meta))
                total += 1

    lines = ["# Recipe index", "",
             "%d recipes. Generated by `scripts/gen_index.py`; do not edit by hand." % total, ""]
    for domain in sorted(rows):
        track = domains[domain].get("track", "")
        lines.append("## %s (%d) — %s track" % (domain, len(rows[domain]), track))
        lines.append("")
        lines.append("| Recipe | Interface | Risk | Status |")
        lines.append("|---|---|---|---|")
        for rel, meta in rows[domain]:
            name = meta.get("name", os.path.splitext(os.path.basename(rel))[0])
            lines.append("| [%s](%s) | %s | %s | %s |" % (
                name, rel, meta.get("interface", "-"), meta.get("risk", "-"),
                meta.get("status", "-")))
        lines.append("")

    # Journeys (long-horizon tasks) — a small curated tier, counted separately from recipes.
    jdir = os.path.join(ROOT, "journeys")
    journeys = []
    if os.path.isdir(jdir):
        for n in sorted(os.listdir(jdir)):
            if not n.endswith(".md") or n in ("README.md", "TEMPLATE.md"):
                continue
            meta = frontmatter(os.path.join(jdir, n))
            if meta.get("kind") != "journey":
                continue
            with open(os.path.join(jdir, n)) as f:
                n_ms = len(re.findall(r"^### +M\d+\b", f.read(), re.M))
            journeys.append(("journeys/" + n, meta, n_ms))
    if journeys:
        lines.append("## journeys (%d) — long-horizon tasks" % len(journeys))
        lines.append("")
        lines.append("Temporal DAGs over the recipes above; see [`journeys/`](journeys/README.md).")
        lines.append("")
        lines.append("| Journey | Horizon | Milestones | Risk | Status |")
        lines.append("|---|---|---|---|---|")
        for rel, meta, n_ms in journeys:
            name = meta.get("name", os.path.splitext(os.path.basename(rel))[0])
            lines.append("| [%s](%s) | %s | %d | %s | %s |" % (
                name, rel, meta.get("horizon", "-"), n_ms, meta.get("risk", "-"),
                meta.get("status", "-")))
        lines.append("")

    with open(os.path.join(ROOT, "INDEX.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("INDEX.md written: %d recipes across %d domains, %d journeys"
          % (total, len(rows), len(journeys)))


if __name__ == "__main__":
    main()
